bump_version: null
lint:
  modules_json: False
  actions_ci: False
  actions_awsfulltest: False
  files_exist:
    - .gitattributes
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .github/workflows/branch.yml
    - assets/multiqc_config.yml
    - CODE_OF_CONDUCT.md
    - .github/workflows/awstest.yml
    - assets/nf-core-needles_logo_light.png
    - .github/workflows/awsfulltest.yml
    - docs/images/nf-core-needles_logo_light.png
    - docs/images/nf-core-needles_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/ci.yml
  files_unchanged:
    - .github/workflows/linting.yml
    - .gitignore
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - .github/workflows/branch.yml
    - CODE_OF_CONDUCT.md
    - conf/igenomes_ignored.config
    - assets/nf-core-needles_logo_light.png
    - docs/images/nf-core-needles_logo_light.png
    - docs/images/nf-core-needles_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/workflows/ci.yml
  multiqc_config: False
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Erin Young
  description: poppunk workflow
  force: true
  is_nfcore: false
  name: needles
  org: erinyoung
  outdir: .
  skip_features: null
  version: 0.0.2411
update: null
